name: lehrlingsquiz CI

on:
  push:
    branches: [main, production]
    pull-request: [main, production]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: clean install packages
        run: npm ci
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
