name: lehrlingsquiz CI

on:
  push:
    branches: [main, production]
    pull-request: [main, production]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: clean install packages
        run: npm ci
      - name: lint(:fix) project files
        run: npm run lint:fix
      - name: run end-2-end tests
        run: npm run e2e
      - name: create production build
        run: npm run build
